import "./style.css";

export const LightModeIcon = () => {
  return (
    <>
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 24 24"
      >
        <circle
          cx="12"
          cy="12"
          r="4"
          stroke="currentColor"
          stroke-width="2"
          fill="none"
        />
        <line
          x1="12"
          y1="2"
          x2="12"
          y2="5"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
        />
        <line
          x1="12"
          y1="19"
          x2="12"
          y2="22"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
        />
        <line
          x1="4.22"
          y1="4.22"
          x2="6.34"
          y2="6.34"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
        />
        <line
          x1="17.66"
          y1="17.66"
          x2="19.78"
          y2="19.78"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
        />
        <line
          x1="2"
          y1="12"
          x2="5"
          y2="12"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
        />
        <line
          x1="19"
          y1="12"
          x2="22"
          y2="12"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
        />
        <line
          x1="4.22"
          y1="19.78"
          x2="6.34"
          y2="17.66"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
        />
        <line
          x1="17.66"
          y1="6.34"
          x2="19.78"
          y2="4.22"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
        />
      </svg>
    </>
  );
};
